### PR TITLE
US 02.02.02 geolocation

### LINKED ISSUE #21: US 02.02.02
As an organizer I want to see on a map where entrants joined my event waiting list from.

### Acceptance Criteria:

- [x] Set up map only for events that have geolocation
- [x] Marker will display entrants accurate location
- [x] Signing up for an event with geolocation should store the entrant's location for later use

### PR DESCRIPTION
**Pull request by Kori-Kozicki**
### Important Details:

- I still think we should remove the checkbox for geolocation since that might cause issues now
- Setting geolocation status is done in the location permission request (which pops up when a user tries to register for an event with geolocation). 
- Location is gotten automatically when a user registers for an event with geolocation, and gets stored in their entrant class. You can test this by checking the logs when you register.
- The map is working completely accurately now. If you have time you should test this too just in case I miss anything

### Demos:

https://github.com/user-attachments/assets/275dea3c-a3fa-418f-91fa-3e213458381e

https://github.com/user-attachments/assets/44ef550f-a36d-4e3e-a3e5-63510c38f0fd

### CheckList

- [x] StoryBoard
- [x] UML
- [x] Unit Testing
- [ ] UI Testing

### CODE REVIEW

**Comment by SuperCreativeUniqueUsername** [comment]
what do you mean check box for geolocation? would that be in post event?

**Comment by Kori-Kozicki** [comment]
> what do you mean check box for geolocation? would that be in post event?

No on the profile fragment. Sorry about that I should've been more specific. The permission request for location will handle setting the geolocation value of the account so having the additional checkbox might cause issues

**Comment by katzhong** [comment]
okay something i'm wondering: for the checkboxes in the profile, would it be a easier or harder implementation for the device permissions to show up when you check the checkbox and the user's location is got through that way? instead of having to click on the register button twice to get registered for an event (with the dialog box)

**Comment by Kori-Kozicki** [comment]
> okay something i'm wondering: for the checkboxes in the profile, would it be a easier or harder implementation for the device permissions to show up when you check the checkbox and the user's location is got through that way? instead of having to click on the register button twice to get registered for an event (with the dialog box)

That would make sense too 🥲
I'll see if I can implement it that way

Edit: Or what I actually can do is put that functionality on the checkbox too and that will be the main way to do it. I want to keep the request on the register button too though for safe measures (because of the permission checking I have to do before I actually access for location info, I'm not sure what I would replace there if I didn't just ask again)

**Comment by Kori-Kozicki** [comment]
> okay something i'm wondering: for the checkboxes in the profile, would it be a easier or harder implementation for the device permissions to show up when you check the checkbox and the user's location is got through that way? instead of having to click on the register button twice to get registered for an event (with the dialog box)

Updated: I set it to go off on the update button instead of the checklist because the update is more final:

https://github.com/user-attachments/assets/79052705-ef05-4245-ab1e-7d1cfd314584

**Comment by katzhong** [comment]
> > okay something i'm wondering: for the checkboxes in the profile, would it be a easier or harder implementation for the device permissions to show up when you check the checkbox and the user's location is got through that way? instead of having to click on the register button twice to get registered for an event (with the dialog box)
> 
> Updated: I set it to go off on the update button instead of the checklist because the update is more final:
> 
>  Profile_location_permission.mp4

okay sorry for this but i think my video was bugging or something when i had initially watched it but i think your initial implementation of this is actually much nicer and more intuitive in terms of user interaction than what i suggested. from my understanding of your implementation, if the user has geolocation enabled in profile, if the user then tries to join an event with geolocation, the app will ask the user if they can have their location, otherwise, some sort of warning saying that geolocation is required so they aren't allowed to join the event and must enable geolocation to do so, correct? up to you if you want to change it back but again, very sorry :(

**Comment by katzhong** [comment]
another thing, i also get what you mean by removing the checkbox for geolocation and i think that makes sense since permission is asked again anyways when getting the location per event

**Comment by Kori-Kozicki** [comment]
> > > okay something i'm wondering: for the checkboxes in the profile, would it be a easier or harder implementation for the device permissions to show up when you check the checkbox and the user's location is got through that way? instead of having to click on the register button twice to get registered for an event (with the dialog box)
> > 
> > 
> > Updated: I set it to go off on the update button instead of the checklist because the update is more final:
> > Profile_location_permission.mp4
> 
> okay sorry for this but i think my video was bugging or something when i had initially watched it but i think your initial implementation of this is actually much nicer and more intuitive in terms of user interaction than what i suggested. from my understanding of your implementation, if the user has geolocation enabled in profile, if the user then tries to join an event with geolocation, the app will ask the user if they can have their location, otherwise, some sort of warning saying that geolocation is required so they aren't allowed to join the event and must enable geolocation to do so, correct? up to you if you want to change it back but again, very sorry :(

☠️ No worries. The pop up when registering should only build if the user didn't have permissions granted. If they did it would just automatically take their location. I think I'll keep the checkbox implementation though because it gives the user more availabilty to change their permission instead of having to do it through their device settings.

**Review by katzhong — APPROVED** [review]

**Comment by Kori-Kozicki** [comment]
> another thing, i also get what you mean by removing the checkbox for geolocation and i think that makes sense since permission is asked again anyways when getting the location per event

It is something we should consider. I was initially up for getting rid of the checkbox but right now it seems intuitive to keep it I think? It depends on everyone else's thoughts too

**Pull request merged**
