### PR TITLE
US 02.01.03 facility managing

### LINKED ISSUE #45: US 02.01.03
As an organizer, I want to create and manage my facility profile.

### Acceptance Criteria:

- [x] Make button that will show the edit fields to "create" an organization
- [x] Allow possibility to update these fields
- [x] Allow image handling
- [x] Facility should automatically show if it already exists

### PR DESCRIPTION
**Pull request by Kori-Kozicki**
### Details:

- Most important note: The facility is considered nonexistant when all of it attributes are null instead of the facility being null itself (because facility is always initialized for new users).
- I'll add UI testing to this PR too but I wanted to get everyone's reviews on it first in case there are design changes.

### Demo:

https://github.com/user-attachments/assets/8fd149e3-5d79-4f98-943f-ce9b41a5f9c2

### Checklist:

- [x] UML
- [x] StoryBoard
- [x] Unit testing (wrote a new one for facility)
- [x] UI testing COMPLETED 🎉🎉🎉

### CODE REVIEW

**Comment by SuperCreativeUniqueUsername** [comment]
I think its kind of annoying for the navigation bar to be visible when we are typing. I know this is not related to your pr but I think this could be something we could try to fix in the future. Regarding your pr, I think it makes sense. I'm wondering what your thoughts are on adding a delete facility button when you're editing. Other than that looks good.

**Comment by Kori-Kozicki** [comment]
> I think its kind of annoying for the navigation bar to be visible when we are typing. I know this is not related to your pr but I think this could be something we could try to fix in the future. Regarding your pr, I think it makes sense. I'm wondering what your thoughts are on adding a delete facility button when you're editing. Other than that looks good.

Yah I agree it is something in need of fixing. Although I'm not sure on how we would do that... hopefully we can fix it before the due date. For delete facility do you mean just the image or the whole facility? Because I did want a delete image button there too but I couldn't figure out how to set the default image to the view after the deleteion (so its a todo if given time). As for deleting the whole facility I could do that easily but there are no user stories for it. So that would just be extra.

**Comment by katzhong** [comment]
looks good! since the facility is being created, would it make more sense to not have 'filled in' fields already? ie. johnson recreation, 10323 112 ave? also, just wondering, is there any error checking in the input fields? like mandatory/optional fields, etc?

**Comment by Kori-Kozicki** [comment]
> looks good! since the facility is being created, would it make more sense to not have 'filled in' fields already? ie. johnson recreation, 10323 112 ave? also, just wondering, is there any error checking in the input fields? like mandatory/optional fields, etc?

Yah I was also thinking those hints in the text fields weren't the greatest. I can remove those.

Right now theres no mandatory fields because I wasn't sure what should be mandatory. What do you think should be?

**Review by SuperCreativeUniqueUsername — APPROVED** [review]
looks good, nice job

**Pull request merged**
