### PR TITLE
Event and Account classes

### PR DESCRIPTION
**Pull request by Jameszf**
I added the Event and Account Java classes.

Feel free to comment about the structure and make suggestions.

### CODE REVIEW

**Review by SuperCreativeUniqueUsername — DISMISSED** [review]
looks good 👍

**Review by Kori-Kozicki — CHANGES_REQUESTED** [review]
I think this looks pretty good. Only points I have is that we forgot to include phone number (and email) as an account attribute and we should document the photo issues in the header comments

**Review by Kori-Kozicki — APPROVED** [review]

**Comment by SuperCreativeUniqueUsername** [comment]
Do you think it would make sense to use getters and setters for data in these classes?

**Review by ghost — APPROVED** [review]
Looks good to me

**Pull request merged**
