### PR TITLE
refactored database, i think it works

### LINKED ISSUE #94: Task: Refactor database classes

### PR DESCRIPTION
**Pull request by SuperCreativeUniqueUsername**
I think it all works

I updated CRC, UML looks so bad but I think its good

### CODE REVIEW

**Review by Jameszf — APPROVED** [review]
Looks good.

I am branching off of this to work on testing.

**Comment by katzhong** [comment]
did you test 💀

**Comment by SuperCreativeUniqueUsername** [comment]
> did you test 💀

i ran it on my phone and it seemed to work

**Review by katzhong — APPROVED** [review]
looks good to me

**Pull request merged**
