### PR TITLE
add geolocation warning

### LINKED ISSUE #44: US 01.08.01
As an entrant, I want to be warned before joining a waiting list that requires geolocation.

### PR DESCRIPTION
**Pull request by katzhong**
added a toast for geolocation if geolocation enabled. crc, uml, etc does not need to be changed. to be updated..... with an additional popup dialog to confirm...

### CODE REVIEW

**Comment by SuperCreativeUniqueUsername** [comment]
Maybe add some testing for the dialog. Other than that it looks good

**Review by Kori-Kozicki — COMMENTED** [review]
The code looks good to me but when I tried to test it, I couldn't find the fragment anywhere. Where was the button to view it again?

edit: Oop nvm I found it. "Scan QR code" was a little misleading. I think this looks good. My only suggestion would be maybe we can make the dialog warning a bit more descriptive. Like "Warning: This event requires geolocation." Otherwise I think it's good.

**Review by Kori-Kozicki — APPROVED** [review]

**Review by Jameszf — APPROVED** [review]
Looks good to me

**Comment by katzhong** [comment]
thanks for the reviews, need to add some tests and yeah, rename some things and add a few/more descriptive comments and description and then i will merge! by 2nite

**Pull request merged**
