### PR TITLE
bug fixed, date removed

### LINKED ISSUE #135: TASK: Remove time view from all events view

### LINKED ISSUE #137: TASK: fix status when accepting or declining an event

### PR DESCRIPTION
**Pull request by SuperCreativeUniqueUsername**
- Removed time from all event pages
- Fixed decline event for redraw error

### CODE REVIEW

**Comment by katzhong** [comment]
looks good! NIT: centre the no button for chance to redraw (no, leave waitlist?), if too much, leave as is is good

**Review by katzhong — APPROVED** [review]

**Review by Kori-Kozicki — APPROVED** [review]
Did we want to set the time to "gone" or "invisible"? Otherwise this looks good to me

**Comment by SuperCreativeUniqueUsername** [comment]
> Did we want to set the time to "gone" or "invisible"? Otherwise this looks good to me

whats the difference?

**Comment by SuperCreativeUniqueUsername** [comment]
> looks good! NIT: centre the no button for chance to redraw (no, leave waitlist?), if too much, leave as is is good

i dont know how to do this programmatic

**Pull request merged**
