### PR TITLE
22 creating event us 02.03.01 and 02.03.03

### LINKED ISSUE #22: US 02.03.01
As an organizer I want to OPTIONALLY limit the number of entrants who can join my waiting list.

- [x] Functionality without database
- [x] Functionality with database

### LINKED ISSUE #46: US 02.02.03
As an organizer I want to enable or disable the geolocation requirement for my event.

- [x] Functionality without database
- [x] Functionality with database
- [ ]  Add this functionality to editing an event

### PR DESCRIPTION
**Pull request by SuperCreativeUniqueUsername**
US 02.03.02: As an organizer I want to OPTIONALLY limit the number of entrants who can join my waiting list.

US 02.03.03: As an organizer I want to enable or disable the geolocation requirement for my event.

Both these requirements are met in this pull request.

Issues: since no database there is no place to store the events created but inside the class I do initialize an event I just need to shove it in the database once that is implemented.

UML and CRC are updated.

UI testing is done for event with no values (error message pops up) and for full event (event is created)

Let me know of anything I've missed

image
image

### CODE REVIEW

**Comment by avreet-14** [comment]
I think the rough diagram seems good but I am not able to see the other half of the diagram

**Comment by SuperCreativeUniqueUsername** [comment]
> I think the rough diagram seems good but I am not able to see the other half of the diagram 

Yeah that's because this pr mainly references this class, the UML is in a shared document. There's a link on our wiki under the the how to do work section.

**Review by Kori-Kozicki — APPROVED** [review]
I think this looks really good. It would be nice if we could eventually get service connection and the my events list page. I've been trying on my end for the database for my list filters but keep getting stumped on how to navigate to test it

**Comment by Jameszf** [comment]
Looks good to me

**Review by Jameszf — APPROVED** [review]
Looks good to me

**Pull request merged**
